### ISSUE TITLE
Get rid of dependency on CUDA runtime library?

### ISSUE THREAD

**Issue by tschwinge** [MentorEmbedded/nvptx-tools#2]
There is currently a dependency in `nvptx-run` on the CUDA runtime library (libcudart) just for the call to `cudaDeviceReset`.  If that is that really necessary, is the a similar function in the CUDA driver library (libcuda), or can this function call be removed altogether?

**Comment by amonakov** [comment]
Indeed it can be removed; done as part of pull request #10.
