### ISSUE TITLE
nvptx-as should not assume a default sm version

### ISSUE THREAD

**Issue by vries** [MentorEmbedded/nvptx-tools#24]
[ See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97348#c1 ]

Nvptx-as has a hardcoded default of sm_30.

Instead, it should use the sm version as specified by the .target line as default.

This makes nvptx-as robust against changes in default sm version in gcc.

**Comment by tschwinge** [comment]
I think I convinced myself that this is indeed the right thing to do.

Do I understand correctly that the idea is that GCC then by default will *not anymore* supply a `-m [...]` option to `nvptx-as`, even if the GCC `-misa=[...]` option has been used?  It doesn't have to, it's redundant.  (That is, `[GCC]/gcc/config/nvptx/nvptx.h:ASM_SPEC` gets removed completely.)

A user may use GCC `-misa=[...]` to select the SM version to generate code for, and that will be embedded in the PTX file as `.target [...]`, and that'll be read by `nvptx-as` and use internally as appropriate (not at present), and passed on to `ptxas` via `--gpu-name [...]`.  Well, this seems to also conceptually match what we've done in libgomp "nvptx plugin: do not force JIT target SM version", GCC commit 0d58938ed798882063737dedfe897a9b484295ad.

Additionally to GCC `-misa=[...]`, a user may use GCC `-Wa,-m,[...]` to force `nvptx-as` (and thus primarily `ptxas` via `--gpu-name [...]) to verify code generation for a different architecture -- if that ever makes sense.

In `nvptx-as`, would we continue to always supply `--gpu-name [...]` to `ptxas` (defaulting to the `.target [...]` we've read in), or only supply `--gpu-name [...]` if there's an explicit `-m [...]` on the `nvptx-as` command line?

**Comment by tschwinge** [comment]
Update: `nvptx-as` has to always override the default `--gpu-name` of `ptxas`: its default may not be sufficient for what is requested in the `.target` directive in the input's preamble ("SM version specified by .target is higher than default SM version assumed").
